//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Cli.commands.install {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.DotNet.Cli.commands.install.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PackageIdArgumentName {
            get {
                return ResourceManager.GetString("PackageIdArgumentName", resourceCulture);
            }
        }
        
        public static string PackageIdArgumentDescription {
            get {
                return ResourceManager.GetString("PackageIdArgumentDescription", resourceCulture);
            }
        }
        
        public static string SpecifyExactlyOnePackageId {
            get {
                return ResourceManager.GetString("SpecifyExactlyOnePackageId", resourceCulture);
            }
        }
        
        public static string VersionOptionName {
            get {
                return ResourceManager.GetString("VersionOptionName", resourceCulture);
            }
        }
        
        public static string VersionOptionDescription {
            get {
                return ResourceManager.GetString("VersionOptionDescription", resourceCulture);
            }
        }
        
        public static string AddSourceOptionName {
            get {
                return ResourceManager.GetString("AddSourceOptionName", resourceCulture);
            }
        }
        
        public static string AddSourceOptionDescription {
            get {
                return ResourceManager.GetString("AddSourceOptionDescription", resourceCulture);
            }
        }
        
        public static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        public static string ConfigFileOptionName {
            get {
                return ResourceManager.GetString("ConfigFileOptionName", resourceCulture);
            }
        }
        
        public static string ConfigFileOptionDescription {
            get {
                return ResourceManager.GetString("ConfigFileOptionDescription", resourceCulture);
            }
        }
        
        public static string FrameworkOptionName {
            get {
                return ResourceManager.GetString("FrameworkOptionName", resourceCulture);
            }
        }
        
        public static string FrameworkOptionDescription {
            get {
                return ResourceManager.GetString("FrameworkOptionDescription", resourceCulture);
            }
        }
        
        public static string NuGetConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("NuGetConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        public static string InstallationSucceeded {
            get {
                return ResourceManager.GetString("InstallationSucceeded", resourceCulture);
            }
        }
        
        public static string LocalToolInstallationSucceeded {
            get {
                return ResourceManager.GetString("LocalToolInstallationSucceeded", resourceCulture);
            }
        }
        
        public static string GlobalOptionDescription {
            get {
                return ResourceManager.GetString("GlobalOptionDescription", resourceCulture);
            }
        }
        
        public static string LocalOptionDescription {
            get {
                return ResourceManager.GetString("LocalOptionDescription", resourceCulture);
            }
        }
        
        public static string InstallFullCommandNameLocalized {
            get {
                return ResourceManager.GetString("InstallFullCommandNameLocalized", resourceCulture);
            }
        }
        
        public static string InvalidToolConfiguration {
            get {
                return ResourceManager.GetString("InvalidToolConfiguration", resourceCulture);
            }
        }
        
        public static string ToolInstallationFailed {
            get {
                return ResourceManager.GetString("ToolInstallationFailed", resourceCulture);
            }
        }
        
        public static string ToolInstallationFailedWithRestoreGuidance {
            get {
                return ResourceManager.GetString("ToolInstallationFailedWithRestoreGuidance", resourceCulture);
            }
        }
        
        public static string ToolInstallationFailedContactAuthor {
            get {
                return ResourceManager.GetString("ToolInstallationFailedContactAuthor", resourceCulture);
            }
        }
        
        public static string ToolInstallationRestoreFailed {
            get {
                return ResourceManager.GetString("ToolInstallationRestoreFailed", resourceCulture);
            }
        }
        
        public static string ToolAlreadyInstalled {
            get {
                return ResourceManager.GetString("ToolAlreadyInstalled", resourceCulture);
            }
        }
        
        public static string FailedToCreateToolShim {
            get {
                return ResourceManager.GetString("FailedToCreateToolShim", resourceCulture);
            }
        }
        
        public static string InvalidNuGetVersionRange {
            get {
                return ResourceManager.GetString("InvalidNuGetVersionRange", resourceCulture);
            }
        }
        
        public static string InstallToolCommandInvalidGlobalAndLocalAndToolPath {
            get {
                return ResourceManager.GetString("InstallToolCommandInvalidGlobalAndLocalAndToolPath", resourceCulture);
            }
        }
        
        public static string ToolPathOptionName {
            get {
                return ResourceManager.GetString("ToolPathOptionName", resourceCulture);
            }
        }
        
        public static string ToolPathOptionDescription {
            get {
                return ResourceManager.GetString("ToolPathOptionDescription", resourceCulture);
            }
        }
        
        public static string ManifestPathOptionDescription {
            get {
                return ResourceManager.GetString("ManifestPathOptionDescription", resourceCulture);
            }
        }
        
        public static string ManifestPathOptionName {
            get {
                return ResourceManager.GetString("ManifestPathOptionName", resourceCulture);
            }
        }
        
        public static string LocalOptionDoesNotSupportFrameworkOption {
            get {
                return ResourceManager.GetString("LocalOptionDoesNotSupportFrameworkOption", resourceCulture);
            }
        }
        
        public static string NoManifestGuide {
            get {
                return ResourceManager.GetString("NoManifestGuide", resourceCulture);
            }
        }
    }
}
