#!/bin/sh
#
# Copyright (c) .NET Foundation and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
#

PACKAGE=$1
INSTALL_DESTINATION=$2


# A temporary fix for the permissions issue(s)
chmod -R 755 $INSTALL_DESTINATION

$INSTALL_DESTINATION/dotnet exec $INSTALL_DESTINATION/sdk/%SDK_VERSION%/dotnet.dll internal-reportinstallsuccess "$1" > /dev/null 2>&1 || true

exit 0
