trigger:
  batch: true
  branches:
    include:
    - master
    - main
    - release/*
    - internal/release/3.*
    - internal/release/5.*
    - internal/release/6.*
  paths:
    exclude:
    - "*.md"

variables:
  - name: teamName
    value: Roslyn-Project-System
  - name: _DotNetPublishToBlobFeed
    value: false
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCore
  - name: PostBuildSign
    value: true
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: _InternalRuntimeDownloadArgs
      value: ''
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: _DotNetPublishToBlobFeed
      value: true
    - group: DotNetBuilds storage account read tokens
    - name: _InternalRuntimeDownloadArgs
      value: /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal 
        /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - group: DotNet-CLI-SDLValidation-Params

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Publish_Build_Configuration
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        vmImage: 'windows-2019'
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: NetCore1ESPool-Internal
        demands: ImageOverride -equals build.windows.10.amd64.vs2019
    steps:
      - publish: $(Build.SourcesDirectory)\eng\BuildConfiguration
        artifact: BuildConfiguration
        displayName: Publish Build Config
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          vmImage: 'windows-2022'
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals Build.Windows.Amd64.VS2022.Pre
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        helixTargetQueue: Windows.Amd64.VS2022.Pre
      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
            _PublishArgs: '-publish /p:DotNetPublishUsingPipelines=true'
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              _SignType: test
              _Test: -test
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              _SignType: real
              _Test: ''
  - template: /eng/common/templates/job/source-build.yml
    parameters:
      platform:
        name: 'Managed'
        container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343'
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_FullFramework
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            vmImage: 'windows-2022'
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals Build.Windows.Amd64.VS2022.Pre
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Windows.Amd64.VS2022.Pre
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishArgs: ''
              _SignType: test
              _Test: -test
            Build_Release:
              _BuildConfig: Release
              _PublishArgs: ''
              _SignType: test
              _Test: -test

    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_TestAsTools
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            vmImage: 'windows-2019'
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals Build.Windows.10.Amd64.VS2019.Pre
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishArgs: ''
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Ubuntu_20_04
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            vmImage: 'ubuntu-20.04'
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals 1es-ubuntu-2004
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: 'ubuntu.2004.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-amd64-20220502145738-4b2e4c2'
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Ubuntu.2004.Amd64
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _PublishArgs: ''
              _SignType: test
              _Test: -test

    - template: /eng/build.yml
      parameters:
        agentOs: Darwin
        pool:
          vmImage: 'macOS-latest'
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: OSX.1015.Amd64.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: OSX.1015.Amd64
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _PublishArgs: ''
              _SignType: test
              _Test: -test

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        publishUsingPipelines: true
        dependsOn:
          - Windows_NT
          - Source_Build_Managed
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals Build.Windows.10.Amd64.VS2019.Pre
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      publishingInfraVersion: 3
      enableSymbolValidation: false
      enableSigningValidation: false
      enableNugetValidation: false
      enableSourceLinkValidation: false
      publishInstallersAndChecksums: true
      SDLValidationParameters:
        enable: false
        params: ' -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL $(_TsaInstanceURL)
        -TsaProjectName $(_TsaProjectName)
        -TsaNotificationEmail $(_TsaNotificationEmail)
        -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
        -TsaBugAreaPath $(_TsaBugAreaPath)
        -TsaIterationPath $(_TsaIterationPath)
        -TsaRepositoryName "dotnet-sdk"
        -TsaCodebaseName "dotnet-sdk"
        -TsaPublish $True'
