trigger:
- master

variables:
  teamName: Roslyn-Project-System
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedKey:
    PB_PublishBlobFeedUrl:
    _DotNetPublishToBlobFeed: false
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedUrl: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    _DotNetPublishToBlobFeed: true

phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    queue:
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        name: Helix
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        name: DotNetCore-Windows
      parallel: 2
      timeoutInMinutes: 120
      matrix:
        ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
        Build_Release:
          _BuildConfig: Release
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: none
            _SignType: test
          ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: blob
            _SignType: real

- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT_FullFramework
      queue:
        name: DotNetCore-Windows
        parallel: 2
        timeoutInMinutes: 120
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test

  - template: /eng/build.yml
    parameters:
      agentOs: Ubuntu_14_04
      queue: 
        name: DotNetCore-Linux
        parallel: 2
        timeoutInMinutes: 120
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

  - template: /eng/build.yml
    parameters:
      agentOs: Ubuntu_16_04
      queue: 
        name: DotNetCore-Linux
        parallel: 2
        timeoutInMinutes: 120
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-e435274-20180628134544

  - template: /eng/build.yml
    parameters:
      agentOs: Darwin
      queue: 
        name: DotNetCore-Mac
        parallel: 2
        timeoutInMinutes: 120
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
