trigger:
- main
- exp/*
- vs*

jobs:
- job: BootstrapMSBuildOnFullFrameworkWindows
  displayName: "Windows Full"
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: CmdLine@2
    displayName: 'Set flag to publish Verify *.received.* files when test step fails'
    condition: failed()
    inputs:
      script: 'echo "##vso[task.setvariable variable=publishverify]Yes"'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'FullOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows test logs'
    continueOnError: true
    condition: always()
  - task: CopyFiles@2
    condition: eq(variables['publishverify'], 'Yes')
    displayName: 'Copy Verify *.received.* files to Artifact Staging'
    inputs:
      contents: '**\*.received.*'
      targetFolder: '$(Build.ArtifactStagingDirectory)\Verify'
      cleanTargetFolder: true
      overWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Verify *.received.* files as Artifacts'
    name: 'verifypublish'
    condition: eq(variables['publishverify'], 'Yes')
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\Verify'
      ArtifactName: 'Windows-on-full Verify $(System.JobAttempt)'


- job: BootstrapMSBuildOnCoreWindows
  displayName: "Windows Core"
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
      arguments: '-msbuildEngine dotnet'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-Core Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-Core .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnWindows test logs'
    continueOnError: true
    condition: always()

- job: FullReleaseOnWindows
  displayName: "Windows Full Release (no bootstrap)"
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: NetCore-Public
      demands: ImageOverride -equals windows.vs2022preview.amd64.open
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      name: VSEngSS-MicroBuild2022-1ES
      demands: agent.os -equals Windows_NT
  steps:
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'eng/cibuild.cmd'
      arguments: '-configuration Release -test'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Release/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Log/Release'
      ArtifactName: 'FullOnWindows Release build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows Release test logs'
    continueOnError: true
    condition: always()

# Unavailable in dnceng-public as of 9/1/2022; should be restored soon.
# - job: RichCodeNavIndex
#   displayName: "Windows Code Indexing"
#   pool:
#     vmImage: 'windows-2022'
#   steps:
#   - task: BatchScript@1
#     displayName: build.cmd
#     inputs:
#       filename: 'build.cmd'
#   - task: RichCodeNavIndexer@0
#     displayName: RichCodeNav Upload
#     inputs:
#       languages: 'csharp'
#     continueOnError: true
#     condition: succeeded()

- job: CoreBootstrappedOnLinux
  displayName: "Linux Core"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: . 'eng/cibuild_bootstrapped_msbuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Linux .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: CmdLine@2
    displayName: 'Set flag to publish Verify *.received.* files when test step fails'
    condition: failed()
    inputs:
      script: 'echo "##vso[task.setvariable variable=publishverify]Yes"'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnLinux build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnLinux test logs'
    continueOnError: true
    condition: always()
  - task: CopyFiles@2
    condition: eq(variables['publishverify'], 'Yes')
    displayName: 'Copy Verify *.received.* files to Artifact Staging'
    inputs:
      contents: '**/*.received.*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/Verify'
      cleanTargetFolder: true
      overWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Verify *.received.* files as Artifacts'
    name: 'verifypublish'
    condition: eq(variables['publishverify'], 'Yes')
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Verify'
      ArtifactName: 'Linux Verify $(System.JobAttempt)'

- job: CoreOnMac
  displayName: "macOS Core"
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: . 'eng/cibuild_bootstrapped_msbuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'macOS .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: CmdLine@2
    displayName: 'Set flag to publish Verify *.received.* files when test step fails'
    condition: failed()
    inputs:
      script: 'echo "##vso[task.setvariable variable=publishverify]Yes"'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnMac build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnMac test logs'
    continueOnError: true
    condition: always()
  - task: CopyFiles@2
    condition: eq(variables['publishverify'], 'Yes')
    displayName: 'Copy Verify *.received.* files to Artifact Staging'
    inputs:
      contents: '**/*.received.*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/Verify'
      cleanTargetFolder: true
      overWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Verify *.received.* files as Artifacts'
    name: 'verifypublish'
    condition: eq(variables['publishverify'], 'Yes')
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Verify'
      ArtifactName: 'macOS Verify $(System.JobAttempt)'

- template: /eng/common/templates/jobs/source-build.yml
