trigger:
- main
- exp/*
- vs*

jobs:
- job: BootstrapMSBuildOnFullFrameworkWindows
  displayName: "Windows Full"
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
    env:
      ForceUseXCopyMSBuild: 1
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'FullOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows test logs'
    continueOnError: true
    condition: always()

- job: BootstrapMSBuildOnCoreWindows
  displayName: "Windows Core"
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
      arguments: '-msbuildEngine dotnet'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-Core Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-Core .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnWindows test logs'
    continueOnError: true
    condition: always()

- job: FullReleaseOnWindows
  displayName: "Windows Full Release (no bootstrap)"
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'eng/cibuild.cmd'
      arguments: '-configuration Release -test'
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
    continueOnError: true
    condition: succeeded()
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Release/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Log/Release'
      ArtifactName: 'FullOnWindows Release build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows Release test logs'
    continueOnError: true
    condition: always()
