#!/bin/sh
ABSOLUTE_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
MSBUILD_SRC_DIR=`dirname $ABSOLUTE_PATH`
#mono $MONO_OPTIONS $MSBUILD_SRC_DIR/bin/Debug-MONO/OSX_Deployment/MSBuild.exe /p:CscToolExe=mcs.exe /p:UseSharedCompilation=false /p:DebugFileExt=.mdb $*
mono $MONO_OPTIONS $MSBUILD_SRC_DIR/bin/Debug-MONO/OSX_Deployment/MSBuild.dll $*
