name: 📉 Performance Issue
description: Report a performance issue or regression.
title: "[Performance]: "
labels: ["performance"]
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: Please include a clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description:  | 
        Include as much of the following as possible: 
        * a minimal sample project that reproduces the issue, 
        * your zipped project, 
        * IDE / CLI steps to create the project and reproduce the behaviour, 
        * your command line invocation.
        
        If providing steps to reproduce the issue proves difficult, consider attaching a binlog:
        * [Details on sharing binary logs](https://aka.ms/msbuild/binlog)
        * [More information on binary logs](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md)
        
        NOTE: Binary logs capture environment information. Ensure it does not include any information you don't want to be public before you attach one.
        If you want to share one just with Microsoft, you can [report a problem through Visual Studio](https://developercommunity.visualstudio.com/report) and share it privately with Microsoft.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Data
      description: |
        Please include all information you've gathered about this performance issue. This includes:
          - Timing
          - Measurements
          - ETW Traces
          - Call stacks
          - Dumps
          - etc.
        If possible please include text as text rather than images (so it shows up in searches).
        If applicable please include before and after measurements.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Analysis
      description: If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
  - type: textarea
    attributes:
      label: Versions & Configurations
      description: |
        In a Visual Studio developer command prompt, run `msbuild -version` and paste the output here.
        If applicable, include the version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc).
        Post any other relevant configuration settings here: OS, architecture, etc.
  - type: checkboxes
    attributes:
      label: Regression
      description: Is this a regression from a previous build/release?
      options:
        - label: "yes"
        - label: "no"
  - type: textarea
    attributes:
      label: Regression Details
      description: |
        Please provide details on regression: what version of MSBuild or VS were you using before the regression?