parameters:
  # Agent OS identifier and used as job name
  agentOs: ''

  # Agent pool
  pool: {}

  # Additional variables
  variables: {}

  # Build strategy - matrix
  strategy: ''

  # Job timeout
  timeoutInMinutes: 180

jobs:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/job/onelocbuild.yml
    parameters:
      CreatePr: false
      LclSource: lclFilesfromPackage
      LclPackageId: 'LCL-JUNO-PROD-DOTNETSDK'
- template: /eng/common/templates/job/job.yml
  parameters:
    name: ${{ parameters.agentOs }}
    enableMicrobuild: true
    enablePublishBuildAssets: true
    enableTelemetry: true
    enablePublishUsingPipelines: true
    helixRepo: dotnet/sdk
    pool: ${{ parameters.pool }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    ${{ if ne(parameters.strategy, '') }}:
      strategy: ${{ parameters.strategy }}
    workspace:
      clean: all
    variables:
      - ${{ insert }}: ${{ parameters.variables }}
      - _AgentOSName: ${{ parameters.agentOs }}
      - _TeamName: DotNetCore
      - _OfficialBuildIdArgs: ''
      - _PublishArgs: ''
      - _SignArgs: ''
      - _HelixApiToken: ''
      # Helix Testing requires a token when internally run
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - group: DotNet-HelixApi-Access
        - _HelixApiToken: $(HelixApiAccessToken)
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - group: dotnet-benchview
        - _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        - _PublishArgs: /p:DotNetPublishUsingPipelines=true
        - _SignArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
        - _PerfIterations: 25

    steps:
    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: PowerShell@2
        displayName: Setup Private Feeds Credentials
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
          arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
        env:
          Token: $(dn-bot-dnceng-artifact-feeds-rw)
    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: eng\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  /p:Test=false
                  $(_InternalRuntimeDownloadArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          HelixAccessToken: ${{ parameters.HelixAccessToken }}
      - powershell: eng\runHelixAndNonHelixInParallel.ps1
              -configuration $(_BuildConfig)
              -buildSourcesDirectory $(Build.SourcesDirectory)
              -customHelixTargetQueue ${{ parameters.helixTargetQueue }}
              $(_Test)
        displayName: Run Tests in Helix and non Helix in parallel
        condition: succeededOrFailed()
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            HelixAccessToken: ''

    - ${{ if eq(parameters.agentOs, 'Windows_NT_FullFramework') }}:
      - script: eng\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  $(_InternalRuntimeDownloadArgs)
                  /p:Test=false
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          TestFullMSBuild: 'true'
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          HelixAccessToken: ${{ parameters.HelixAccessToken }}
      - powershell: eng\runHelixAndNonHelixInParallel.ps1
              -configuration $(_BuildConfig)
              -buildSourcesDirectory $(Build.SourcesDirectory)
              -customHelixTargetQueue ${{ parameters.helixTargetQueue }}
              $(_Test)
        displayName: Run Tests in Helix and non Helix in parallel
        condition: succeededOrFailed()
        env:
            TestFullMSBuild: 'true'
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            HelixAccessToken: ''

    - ${{ if eq(parameters.agentOs, 'Windows_NT_TestAsTools') }}:
      - script: eng\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  $(_Test)
                  $(_InternalRuntimeDownloadArgs)
                  /p:RunTestsAsTool=true
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)

    - ${{ if notIn(parameters.agentOs, 'Windows_NT', 'Windows_NT_FullFramework', 'Windows_NT_TestAsTools') }}:
      - script: eng/common/cibuild.sh
                  --configuration $(_BuildConfig)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  $(_InternalRuntimeDownloadArgs)
                  -p:Test=false
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
      - script: eng/runTestsCannotRunOnHelix.sh
                  --configuration $(_BuildConfig)
                  --ci
                  $(_OfficialBuildIdArgs)
        displayName: Run Tests Cannot Run On Helix
        env:
          BuildConfig: $(_BuildConfig)
      - script: eng/common/build.sh
              --configuration $(_BuildConfig)
              --prepareMachine
              --ci
              --restore
              --test
              --projects $(Build.SourcesDirectory)/src/Tests/UnitTests.proj
              /bl:$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)/TestInHelix.binlog
              /p:_CustomHelixTargetQueue=${{ parameters.helixTargetQueue }}
        displayName: Run Tests in Helix
        condition: succeededOrFailed()
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            HelixAccessToken: $(_HelixApiToken)

    - task: PublishTestResults@2
      displayName: Publish Test Results	
      inputs:	
        testResultsFormat: xUnit	
        testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'	
        testRunTitle: '$(_AgentOSName)_$(Agent.JobName)'	
        buildPlatform: '$(BuildPlatform)'	
        buildConfiguration: '$(_BuildConfig)'	
      condition: always()

    - task: CopyFiles@2	
      displayName: Gather Logs	
      inputs:	
        SourceFolder: '$(Build.SourcesDirectory)/artifacts'	
        Contents: |	
         log/$(_BuildConfig)/**/*	
         TestResults/$(_BuildConfig)/**/*	
         SymStore/$(_BuildConfig)/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'	
      continueOnError: true	
      condition: always()

    - task: PublishBuildArtifacts@1	
      displayName: Publish Logs to VSTS	
      inputs:	
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'	
        ArtifactName: '$(_AgentOSName)_$(Agent.JobName)_$(Build.BuildNumber)'	
        publishLocation: Container	
      continueOnError: true	
      condition: always()
