// <auto-generated>
using System.Reflection;


namespace Microsoft.DotNet
{
    internal static partial class DotnetCommonLocalizableStrings
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(DotnetCommonLocalizableStrings)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }
#if !NET20
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
#endif
        internal static string GetResourceString(string resourceKey, string defaultValue = null) => ResourceManager.GetString(resourceKey, Culture);
        /// <summary>MSBuild server</summary>
        internal static string @PathUtilitiesMkdirFailure => GetResourceString("PathUtilitiesMkdirFailure");

    }
}
