#!/bin/sh
#
# Copyright (c) .NET Foundation and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
#

PACKAGE=$1
INSTALL_DESTINATION=$2


# A temporary fix for the permissions issue(s)
chmod -R 755 $INSTALL_DESTINATION

# Add the installation bin directory to the system-wide paths
echo $INSTALL_DESTINATION/bin | tee -a /etc/paths.d/dotnet


exit 0
