#!/bin/sh
#
# Copyright (c) .NET Foundation and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
#

ln -s $2/dotnet /usr/local/bin/
ln -s $2/dotnet-compile /usr/local/bin/
ln -s $2/dotnet-compile-csc /usr/local/bin/
ln -s $2/dotnet-publish /usr/local/bin/
ln -s $2/dotnet-restore /usr/local/bin/
ln -s $2/dotnet-restore /usr/local/bin/
ln -s $2/resgen /usr/local/bin/

exit 0
