name: Inter-branch merge workflow
on:
  push:
    branches:
      - vs1**

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: '.config/git-merge-flow-config.jsonc'