name: Validate PerfStar action

on:
  pull_request:
    paths:
      - .github/actions/perfstar/**
      - .github/workflows/perfstar-branch.yml
      - .github/workflows/perfstar-action-validation.yml
  push:
    branches: [main]
    paths:
      - .github/actions/perfstar/**
      - .github/workflows/perfstar-branch.yml
      - .github/workflows/perfstar-action-validation.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate action
        working-directory: .github/actions/perfstar
        run: |
          npm ci
          npm run validate
